; ========================
; General
; ========================
date.timezone = Asia/Tashkent
memory_limit = 1024M
max_execution_time = 60
max_input_time = 60
max_input_vars = 5000

upload_max_filesize = 256M
post_max_size = 256M

; Ko‘p worker bilan ishlash uchun file descriptors limitini oshirish
realpath_cache_size = 4096K
realpath_cache_ttl = 600

; ========================
; Security
; ========================
expose_php = Off
cgi.fix_pathinfo = 0
session.cookie_httponly = 1
session.use_strict_mode = 1
session.cookie_secure = 1
session.use_only_cookies = 1

; ========================
; Errors
; ========================
display_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE

; ========================
; OPcache
; ========================
[opcache]
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=1024
opcache.interned_strings_buffer=128
opcache.max_accelerated_files=200000
opcache.max_wasted_percentage=5
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.fast_shutdown=1
opcache.file_update_protection=0
opcache.jit_buffer_size=512M
opcache.jit=tracing

; ========================
; Session (Redis ishlatsa yaxshi)
; ========================
session.gc_maxlifetime = 1440
session.save_handler = redis
session.save_path = "tcp://redis:6379?database=1"

; ========================
; FPM ishlashini yengillashtirish
; ========================
output_buffering = 4096
request_order = "GP"
